home_control_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    path(
        "update/", include("firmware_manager.urls")
    ),  # Rute pentru ESP32 și date seriale
    path("", include("light_app.urls")),
    path("summernote/", include("django_summernote.urls")),
]

light_app/urls.py
from django.urls import path
from . import views

# Define the URL patterns for the light app.
urlpatterns = [
    path("", views.home, name="home"),  # Home page route.

    path("settings/", views.user_settings_view, name="user_settings"),
    # Route for user settings page.

    path("toggle-light/<str:room_name>/<str:light_name>/", views.toggle_light,
         name="toggle_light",),
    # Route to toggle the light in a specific room and light by their names.

    path("rooms/", views.room_list_view, name="room_list"),
    # Route to display the list of rooms.

    path("lights_status/", views.lights_status, name="lights_status"),
    # Route to check the status of lights.

    path("add_room/", views.add_room, name="add_room"),
    # Route to add a new room.

    path("edit_room/<int:room_id>/", views.edit_room, name="edit_room"),
    # Route to edit an existing room by its ID.

    path("delete_room/<int:room_id>/", views.delete_room, name="delete_room"),
    # Route to delete a room by its ID.

    path("add_light/", views.add_light, name="add_light"),
    # Route to add a new light.

    path("edit_light/<int:light_id>/", views.edit_light, name="edit_light"),
    # Route to edit an existing light by its ID.

    path("delete_light/<int:light_id>/",
         views.delete_light, name="delete_light"),
    # Route to delete a light by its ID.

    path("check_home_status/", views.check_home_status,
         name="check_home_status"),
    # Route to check the current status of the home (online/offline).
]

light_app/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# =============================================================================
# Choices for light state (on, off, timer)
STATE_CHOICES = [
    (1, "on"),
    (2, "off"),
    (3, "timer"),
]

# =============================================================================


class Choice(models.Model):
    """
    A model to represent a generic choice that can be associated with a Light.

    Fields:
    - name: Name of the choice.
    """

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]

# =============================================================================


class Room(models.Model):
    """
    A model representing a room owned by a specific user.

    Fields:
    - name: Name of the room.
    - user: A foreign key referencing the user who owns the room.
    """

    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name="rooms")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        unique_together = ("name", "user")

# =============================================================================


class Light(models.Model):
    """
    A model to represent a light in a room. Each light is associated with a 
    room and can have a state.

    Fields:
    - name: Name of the light.
    - room: Foreign key to the Room model.
    - description: Optional description of the light.
    - state: Current state of the light, chosen from STATE_CHOICES.
    - choices: Many-to-many relationship with the Choice model.
    """

    name = models.CharField(max_length=100, default="")
    room = models.ForeignKey(
        Room, on_delete=models.CASCADE, related_name="lights")
    description = models.TextField(null=True, blank=True, default="")
    state = models.IntegerField(choices=STATE_CHOICES, default=2)
    choices = models.ManyToManyField(Choice, related_name="lights", blank=True)

    def __str__(self):
        return f"{self.name} in {self.room}"

    class Meta:
        ordering = ["id"]

# =============================================================================


class UserSettings(models.Model):
    """
    A model to store user-specific settings, including notification
      preferences, theme, and more.

    Fields:
    - user: One-to-one relationship with the Django User model.
    - api_password: Password used for API authentication.
    - server_check_interval: Interval (in seconds) for checking server status.
    - display_name: Display name of the user.
    - email: Email address of the user.
    - preferred_language: The user's preferred language.
    - timezone: The user's timezone.
    - theme: UI theme setting (light or dark).
    - font_size: Preferred font size.
    - primary_color: User's selected primary color for the UI.
    - email_notifications: Boolean to indicate if email notifications are 
    enabled.
    - push_notifications: Boolean to indicate if push notifications are 
    enabled.
    - two_factor_authentication: Boolean to indicate if 2FA is enabled.
    - scheduled_lights: Boolean to indicate if the user has scheduled lights.
    - silence_mode: Boolean to enable or disable silence mode.
    - test_mode: Boolean to indicate if the user is in test mode.
    - m5core2_ip: IP address for the M5Core2 device.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    api_password = models.CharField(max_length=128)  # API password

    server_check_interval = models.IntegerField(
        default=5, help_text="Interval in seconds for checking server status."
    )

    display_name = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=255, blank=True)
    preferred_language = models.CharField(max_length=50,choices=[("en", "English"), ("fr","French"), ("de", "German")],
        default="en",
    )
    timezone = models.CharField(max_length=50, default="UTC")
    theme = models.CharField(
        max_length=10, choices=[("light", "Light"), ("dark", "Dark")],
        default="light"
    )
    font_size = models.CharField(max_length=10,choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
        default="medium",
    )
    primary_color = models.CharField(max_length=7, default="#2980b9")  # Default color is blue
    email_notifications = models.BooleanField(default=True)
    push_notifications = models.BooleanField(default=True)
    two_factor_authentication = models.BooleanField(default=False)
    scheduled_lights = models.BooleanField(default=False)
    silence_mode = models.BooleanField(default=False)
    test_mode = models.BooleanField(default=True)
    # User's M5Core2 IP address
    m5core2_ip = models.CharField(max_length=100, blank=True, default="")

    def save(self, *args, **kwargs):
        """
        Custom save method that ensures the server check interval is between 1
          second and 7200 seconds (2 hours).
        """
        if self.server_check_interval < 1:
            self.server_check_interval = 1
        elif self.server_check_interval > 7200:
            self.server_check_interval = 7200
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.user.username} Settings"

light_app/views.py
import os
import requests

from django.core.paginator import Paginator
from django.core.cache import cache
from django.db import connections
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.translation import gettext as _
from django.utils.functional import SimpleLazyObject

from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from .models import Room, Light, UserSettings
from .forms import RoomForm, LightForm, UserSettingsForm
from .context_processors import home_online_status, debug

# Global variables
user_id = False
ping_active = True


def home(request):
    """
    Renders the home page for authenticated users.

    This function handles the HTTP GET request and renders the
    home page template `index.html` for authenticated users.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: The rendered home page template.
    """
    return render(request, "light_app/index.html")


@login_required
def check_home_status(request):
    """
    Returns the current online status of the user's home automation system.

    This function checks the global 'home_online_status' variable for the
    status of the home system specific to the authenticated user.
    The status is returned as a JSON response.

    Args:
        request: The HTTP request object containing user information.

    Returns:
        JsonResponse: A JSON object containing the home online status
        for the authenticated user.
    """
    global home_online_status
    user_id = request.user.id
    return JsonResponse({"home_online_status":
                         home_online_status.get(user_id)})


# =============================================================================

@login_required
def user_settings_view(request):
    """
    Displays and processes the user settings form for authenticated users.

    This function handles both GET and POST requests. On GET, it retrieves the
    existing user settings or creates a new instance if none exists,
      and displays
    the settings form. On POST, it processes the form, saves any valid changes,
    and redirects the user to the home page upon successful form submission.

    Args:
        request: The HTTP request object containing user information
          and form data.

    Returns:
        HttpResponse: If the request method is GET, renders the user
          settings form.
        If the request method is POST and the form is valid, redirects to the
          home page.
    """
    user_settings, created = UserSettings.objects.get_or_create(
        user=request.user
        )
    form = UserSettingsForm(instance=user_settings)

    if request.method == "POST":
        form = UserSettingsForm(request.POST, instance=user_settings)

        if form.is_valid():
            form.save()
            # Redirect to the home page after successful save
            return redirect("home")

    return render(
        request,
        "light_app/user_settings.html",
        {
            "form": form,
        },
    )


# =============================================================================

@login_required
def room_list_view(request):
    """
    Displays a list of rooms for the authenticated user, with pagination.

    Retrieves all rooms associated with the authenticated user and paginates
    the result to show 3 rooms per page.It then renders the room list template.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: The rendered rooms list template with paginated rooms.
    """
    rooms = Room.objects.filter(user=request.user).prefetch_related("lights")
    paginator = Paginator(rooms, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "room_list": page_obj,
        "is_paginated": page_obj.has_other_pages(),
        "page_obj": page_obj,
    }
    return render(request, "light_app/rooms_list.html", context)

# =============================================================================


def lights_status(request):
    """
    Returns the status of all lights in all rooms.

    Retrieves all rooms and their associated lights, then returns a JSON
    response containing the state of each light ("on" or "off").

    Args:
        request: The HTTP request object.

    Returns:
        JsonResponse: A JSON list containing the status of lights in each room.
    """
    lights_data = []
    rooms = Room.objects.all()
    for room in rooms:
        lights = room.lights.all()
        for light in lights:
            lights_data.append(
                {
                    "room": room.name,
                    "light": light.name,
                    "state": "on" if light.state == 1 else "off",
                }
            )
    return JsonResponse(lights_data, safe=False)

# =============================================================================


@login_required
def toggle_light(request, room_name, light_name):
    """
    Toggles the state of a light in the specified room.

    Finds the room and light by their names for the authenticated user,
    toggles the light state (on/off), and communicates the change to the
    ESP32 device if the user's IP address is configured.
    Returns a JSON response for AJAX requests or redirects to the room list.

    Args:
        request: The HTTP request object.
        room_name: The name of the room.
        light_name: The name of the light.

    Returns:
        JsonResponse or HttpResponse: If the request is AJAX, returns the
        light state in a JSON response, otherwise redirects to the room list.
    """
    room = get_object_or_404(Room, name=room_name, user=request.user)
    light = get_object_or_404(Light, room=room, name=light_name)

    user_ip = request.user_ip
    if not user_ip or user_ip == "none":
        return JsonResponse({"error": "ESP32 IP not configured for user",
                            "action": "go_to_settings"}, status=400,)
    response_text = ""
    action = "off" if light.state == 1 else "on"

    if user_ip:
        try:
            try:
                response = requests.get(
                    f"http://{request.user_ip}", timeout=30)
                if response.status_code == 200:
                    home_online = True
            except requests.exceptions.RequestException as e:
                home_online = False
                response_text = f"Server offline: {e}"

            if home_online:
                response = requests.get(
                    f"http://{request.user_ip}/control_led",
                    params={
                        "room": room_name,
                        "light": light_name,
                        "action": action
                    },
                    timeout=30,
                )

                if response.ok:
                    light.state = 1 if action == "on" else 2
                    light.save()
                    response_text = response.json()
                else:
                    response_text = "Failed to change light state on M5Core2\
                          server."
        except Exception as e:
            response_text = f"Error: {e}"

    if request.headers.get("x-requested-with") == "XMLHttpRequest":
        return JsonResponse(
            {"state": light.get_state_display(), "esp_response": response_text}
        )

    return redirect("room_list")

# =============================================================================


@login_required
def add_room(request):
    """
    Handles the addition of a new room for the authenticated user.

    Renders a form for creating a new room. If the request method is POST,
    validates and saves the new room, associating it with the current user.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: The rendered room addition form or redirects
          to the room list.
    """
    if request.method == "POST":
        form = RoomForm(request.POST)
        if form.is_valid():
            room = form.save(commit=False)
            room.user = request.user
            room.save()
            return redirect("room_list")
    else:
        form = RoomForm()

    return render(request, "light_app/add_room.html", {"form": form})

# =============================================================================


@login_required
def add_light(request):
    """
    Handles the addition of a new light for the authenticated user.

    Renders a form for creating a new light. If the request method is POST,
    validates and saves the new light, ensuring it is associated with the
    correct room.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: The rendered light addition form or redirects to the
          room list.
    """
    if request.method == "POST":
        form = LightForm(request.POST, user=request.user)
        if form.is_valid():
            light = form.save(commit=False)
            light.room.user = request.user
            light.save()
            return redirect("room_list")
    else:
        form = LightForm(user=request.user)

    return render(request, "light_app/add_light.html", {"form": form})

# =============================================================================


@login_required
def edit_room(request, room_id):
    """
    Handles editing of an existing room for the authenticated user.

    Retrieves the room by its ID and renders a form for editing the room.
    If the request method is POST, validates and saves the updated room.

    Args:
        request: The HTTP request object.
        room_id: The ID of the room to be edited.

    Returns:
        HttpResponse:The rendered room edit form or redirects to the room list.
    """
    room = get_object_or_404(Room, id=room_id, user=request.user)

light_app/templates/light_app/add_light.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h2>Add a new light</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add Light</button>
    </form>
</div>
{% endblock %}

light_app/templates/light_app/add_room.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container">
    <h2>Add a new room</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add Room</button>
    </form>
</div>
{% endblock %}

light_app/templates/light_app/delete_light.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h2>Delete Light: {{ light.name }}</h2>
    <p>Are you sure you want to delete this light?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, delete</button>
        <a href="{% url 'room_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

light_app/templates/light_app/delete_room.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h2>Delete Room: {{ room.name }}</h2>
    <p>Are you sure you want to delete <b> {{ room.name.upper }} </b>room?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, delete</button>
        <a href="{% url 'room_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

light_app/templates/light_app/edit_light.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h2>Edit Light: {{ light.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>
{% endblock %}

light_app/templates/light_app/edit_room.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h2>Edit Room: {{ room.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>
{% endblock %}

light_app/templates/light_app/index.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}

<div class="container text-center mt-5">
    <h1 class="display-4">Welcome to  Smart Home </h1>
    <p class="lead">This is a simple Django project designed to manage and control smart devices in a home environment.</p>
    
    <div class="row mt-5">
        <div class="col-md-6 mb-4">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h2 class="card-title">Manage Rooms & Control Lights</h2>
                    <p class="card-text">Organize your smart devices by room. Switch your lights on and off with ease. Monitor the status of all your lights in real-time. Add, edit, or delete rooms as needed.</p>
                    {% if user.is_authenticated %}
                    <a class="btn btn-primary btn-lg mt-3" href="{% url 'room_list' %}">View Rooms</a>
                    {% else %}
                    <a class="btn btn-warning btn-lg mt-3" aria-current="page" href="{% url 'account_signup' %}">Register</a>
                    <a class="btn btn-secondary btn-lg mt-3" aria-current="page" href="{% url 'account_login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="col-md-6 mb-4">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h2 class="card-title">Customize Settings</h2>
                    <p class="card-text">Customize your smart home settings to suit your preferences.
                    </p>
                    {% if user.is_authenticated %}
                    <a class="btn btn-warning btn-lg mt-3" href="{% url 'user_settings' %}">Settings</a>
                    {% else %}
                    <div class="alert alert-warning" role="alert">
                        You need to <a href="{% url 'account_login' %}" class="alert-link">log in</a> to customize your smart home settings.
                      </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

</div>

{% if user.is_authenticated %}
<div id="topNotification" class="alert alert-success alert-dismissible fade show" role="alert" style="display: none;">
    Welcome to Smart Home System!
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

{% endif %}


<script>
    document.addEventListener("DOMContentLoaded", function () {
        const notification = document.getElementById('topNotification');
        if (notification) {
            notification.style.display = 'block';
            setTimeout(function () {
                notification.style.display = 'none';
            }, 3000);
        }
    });

</script>

{% endblock %}

light_app/templates/light_app/user_settings.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center">User Settings</h2>
    <form method="POST" class="mt-3">
        {% csrf_token %}

        <div class="row mb-3">
            <label for="id_display_name" class="col-sm-3 col-form-label">Display Name</label>
            <div class="col-sm-9">
                {{ form.display_name }}
            </div>
        </div>

        <div class="row mb-3">
            <label for="id_email" class="col-sm-3 col-form-label">Email</label>
            <div class="col-sm-9">
                {{ form.email }}
            </div>
        </div>

        <div class="row mb-3">
            <label for="id_preferred_language" class="col-sm-3 col-form-label">Preferred Language</label>
            <div class="col-sm-9">
                {{ form.preferred_language }}
            </div>
        </div>

        <div class="row mb-3">
            <label for="id_timezone" class="col-sm-3 col-form-label">Timezone</label>
            <div class="col-sm-9">
                {{ form.timezone }}
            </div>
        </div>

        <div class="row mb-3">
            <label for="id_theme" class="col-sm-3 col-form-label">Theme</label>
            <div class="col-sm-9">
                {{ form.theme }}
            </div>
        </div>

        <div class="row mb-3">
            <label for="id_font_size" class="col-sm-3 col-form-label">Font Size</label>
            <div class="col-sm-9">
                {{ form.font_size }}
            </div>
        </div>

        <div class="row mb-3">
            <label for="id_primary_color" class="col-sm-3 col-form-label">Primary Color</label>
            <div class="col-sm-9">
                {{ form.primary_color }}
            </div>
        </div>

        <div class="row mb-3">
            <label for="id_email_notifications" class="col-sm-3 col-form-label">Email Notifications</label>
            <div class="col-sm-9">
                <label class="switch">
                    {{ form.email_notifications }}
                    <span class="slider round"></span>
                </label>
            </div>
        </div>

        <div class="row mb-3">
            <label for="id_push_notifications" class="col-sm-3 col-form-label">Push Notifications</label>
            <div class="col-sm-9">
                <label class="switch">
                    {{ form.push_notifications }}
                    <span class="slider round"></span>
                </label>
            </div>
        </div>

        <div class="row mb-3">
            <label for="id_two_factor_authentication" class="col-sm-3 col-form-label">Two Factor Authentication</label>
            <div class="col-sm-9">
                <label class="switch">
                    {{ form.two_factor_authentication }}
                    <span class="slider round"></span>
                </label>
            </div>
        </div>

        <div class="row mb-3">
            <label for="id_scheduled_lights" class="col-sm-3 col-form-label">Scheduled Lights</label>
            <div class="col-sm-9">
                <label class="switch">
                    {{ form.scheduled_lights }}
                    <span class="slider round"></span>
                </label>
            </div>
        </div>

        <div class="row mb-3">
            <label for="id_silence_mode" class="col-sm-3 col-form-label">Silence Mode</label>
            <div class="col-sm-9">
                <label class="switch">
                    {{ form.silence_mode }}
                    <span class="slider round"></span>
                </label>
            </div>
        </div>
        <div class="row mb-3">
            <label for="id_test_mode" class="col-sm-3 col-form-label">Test Mode</label>
            <div class="col-sm-9">
                <label class="switch">
                    {{ form.test_mode }}
                    <span class="slider round"></span>
                </label>
            </div>
        </div>

        <div class="row mb-3">
            <label for="id_m5core2_ip" class="col-sm-3 col-form-label">M5Core2 IP Address</label>
            <div class="col-sm-9">
                {{ form.m5core2_ip }}
            </div>
        </div>

        <div class="row mb-3">
            <label for="id_server_check_interval" class="col-sm-3 col-form-label">Server Check Interval</label>
            <div class="col-sm-9">
                {{ form.server_check_interval }}
            </div>
        </div>

        <div class="row">
            <div class="col-sm-9 offset-sm-3">
                <button type="submit" class="btn btn-primary">Save and go to main page</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}